package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/barrybeics/botServer/database"
	"github.com/barrybeics/botServer/graph/model"
)

// CreateActivityReport is the resolver for the createActivityReport field.
func (r *mutationResolver) CreateActivityReport(ctx context.Context, input *model.NewActivityReport) (*model.ActivityReport, error) {
	return db.SaveActivityReport(input), nil
}

// ActivityReport is the resolver for the ActivityReport field.
func (r *queryResolver) ActivityReport(ctx context.Context, id string) (*model.ActivityReport, error) {
	return db.FindActivityReportByID(id), nil
}

// ActivityReports is the resolver for the ActivityReports field.
func (r *queryResolver) ActivityReports(ctx context.Context) ([]*model.ActivityReport, error) {
	return db.AllActivityReports(), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var db = database.Connect()
