package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/barrybeics/botServer/graph/model"
	"github.com/rs/zerolog/log"
)

// CreateHistoricPrices is the resolver for the createHistoricPrices field.
func (r *mutationResolver) CreateHistoricPrices(ctx context.Context, input *model.NewHistoricPriceInput) ([]*model.HistoricPrices, error) {
	// Assuming you want to save multiple HistoricPrices in the input
	insertedHistoricPrices, err := db.SaveHistoricPrices(input)
	if err != nil {
		return nil, err
	}

	// Assuming you want to return the insertedHistoricPrices and the timestamp
	return insertedHistoricPrices, nil
}

// DeleteHistoricPrices is the resolver for the deleteHistoricPrices field.
func (r *mutationResolver) DeleteHistoricPrices(ctx context.Context, timestamp int) (bool, error) {
	err := db.DeleteHistoricPricesByTimestamp(ctx, timestamp)

	if err != nil {
		log.Error().Err(err).Msg("Error getting Unique Timestamp Count")
		return false, err
	}

	return true, nil
}

// GetHistoricPrice is the resolver for the getHistoricPrice field.
func (r *queryResolver) GetHistoricPrice(ctx context.Context, symbol string, limit *int) ([]*model.HistoricPrices, error) {
	historicPrices, err := db.HistoricPricesBySymbol(symbol, *limit)
	if err != nil {
		log.Error().Err(err).Msg("Error getting historic prices")
		return nil, err
	}

	// Convert slice of model.HistoricPrice to slice of *model.HistoricPrice
	var result []*model.HistoricPrices
	for i := range historicPrices {
		result = append(result, &historicPrices[i])
	}

	// Return the slice of pointers to historic prices
	return result, nil
}

// GetHistoricPricesAtTimestamp is the resolver for the getHistoricPricesAtTimestamp field.
func (r *queryResolver) GetHistoricPricesAtTimestamp(ctx context.Context, timestamp int) ([]*model.HistoricPrices, error) {
	historicPrices, err := db.HistoricPricesAtTimestamp(timestamp)
	if err != nil {
		log.Error().Err(err).Msg("Error getting historic prices at position")
		return nil, err
	}

	// Convert slice of model.HistoricPrices to slice of *model.HistoricPrices
	var result []*model.HistoricPrices
	for i := range historicPrices {
		result = append(result, &historicPrices[i])
	}

	// Return the slice of pointers to historic prices
	return result, nil
}

// GetUniqueTimestampCount fetches the count of unique timestamps.
func (r *queryResolver) GetUniqueTimestampCount(ctx context.Context) (int, error) {
	int, err := db.GetUniqueTimestampCount(ctx)

	if err != nil {
		log.Error().Err(err).Msg("Error getting Unique Timestamp Count")
		return 0, err
	}

	return int, nil
}
