// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ActivityReport struct {
	ID        string  `json:"_id"`
	Timestamp string  `json:"Timestamp"`
	Qty       int     `json:"Qty"`
	AvgGain   float64 `json:"AvgGain"`
}

type NewActivityReport struct {
	Timestamp string  `json:"Timestamp"`
	Qty       int     `json:"Qty"`
	AvgGain   float64 `json:"AvgGain"`
}

type QueryActivityReport struct {
	ActivityReport  *ActivityReport   `json:"ActivityReport"`
	ActivityReports []*ActivityReport `json:"ActivityReports"`
}
